/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public interface consensusConstants {
  public final static String LIBBITCOIN_CONSENSUS_VERSION = consensusJNI.LIBBITCOIN_CONSENSUS_VERSION_get();
  public final static int LIBBITCOIN_CONSENSUS_MAJOR_VERSION = consensusJNI.LIBBITCOIN_CONSENSUS_MAJOR_VERSION_get();
  public final static int LIBBITCOIN_CONSENSUS_MINOR_VERSION = consensusJNI.LIBBITCOIN_CONSENSUS_MINOR_VERSION_get();
  public final static int LIBBITCOIN_CONSENSUS_PATCH_VERSION = consensusJNI.LIBBITCOIN_CONSENSUS_PATCH_VERSION_get();
}
