/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class consensusJNI {
  public final static native String LIBBITCOIN_CONSENSUS_VERSION_get();
  public final static native int LIBBITCOIN_CONSENSUS_MAJOR_VERSION_get();
  public final static native int LIBBITCOIN_CONSENSUS_MINOR_VERSION_get();
  public final static native int LIBBITCOIN_CONSENSUS_PATCH_VERSION_get();
  public final static native int verify_result_eval_false_get();
  public final static native int verify_flags_none_get();
  public final static native int verify_flags_p2sh_get();
  public final static native int verify_flags_strictenc_get();
  public final static native int verify_flags_dersig_get();
  public final static native int verify_flags_low_s_get();
  public final static native int verify_flags_nulldummy_get();
  public final static native int verify_flags_sigpushonly_get();
  public final static native int verify_flags_minimaldata_get();
  public final static native int verify_flags_discourage_upgradable_nops_get();
  public final static native int verify_flags_cleanstack_get();
  public final static native int verify_script(long jarg1, long jarg2, long jarg3, long jarg4, long jarg5, long jarg6);
}
