/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class verify_flags {
  public final static verify_flags verify_flags_none = new verify_flags("verify_flags_none", consensusJNI.verify_flags_none_get());
  public final static verify_flags verify_flags_p2sh = new verify_flags("verify_flags_p2sh", consensusJNI.verify_flags_p2sh_get());
  public final static verify_flags verify_flags_strictenc = new verify_flags("verify_flags_strictenc", consensusJNI.verify_flags_strictenc_get());
  public final static verify_flags verify_flags_dersig = new verify_flags("verify_flags_dersig", consensusJNI.verify_flags_dersig_get());
  public final static verify_flags verify_flags_low_s = new verify_flags("verify_flags_low_s", consensusJNI.verify_flags_low_s_get());
  public final static verify_flags verify_flags_nulldummy = new verify_flags("verify_flags_nulldummy", consensusJNI.verify_flags_nulldummy_get());
  public final static verify_flags verify_flags_sigpushonly = new verify_flags("verify_flags_sigpushonly", consensusJNI.verify_flags_sigpushonly_get());
  public final static verify_flags verify_flags_minimaldata = new verify_flags("verify_flags_minimaldata", consensusJNI.verify_flags_minimaldata_get());
  public final static verify_flags verify_flags_discourage_upgradable_nops = new verify_flags("verify_flags_discourage_upgradable_nops", consensusJNI.verify_flags_discourage_upgradable_nops_get());
  public final static verify_flags verify_flags_cleanstack = new verify_flags("verify_flags_cleanstack", consensusJNI.verify_flags_cleanstack_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static verify_flags swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + verify_flags.class + " with value " + swigValue);
  }

  private verify_flags(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private verify_flags(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private verify_flags(String swigName, verify_flags swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static verify_flags[] swigValues = { verify_flags_none, verify_flags_p2sh, verify_flags_strictenc, verify_flags_dersig, verify_flags_low_s, verify_flags_nulldummy, verify_flags_sigpushonly, verify_flags_minimaldata, verify_flags_discourage_upgradable_nops, verify_flags_cleanstack };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

