/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.bitcoin.libconsensus;

public interface consensusConstants {
  public final static String LIBBITCOIN_CONSENSUS_VERSION = consensusJNI.LIBBITCOIN_CONSENSUS_VERSION_get();
}
